#%RAML 0.8
---
title: Test API
baseUri: http://api.foo.com/v2
version: v1
mediaType: application/json
protocols: [HTTPS, HTTP]

traits:
    - authenticated:
        usage: Apply to any method which requires a user to be authenticated via JWT

/user:
    /whoami:
        get:
            is: [authenticated]
            displayName: Who am I?
            description: |
                Get details on the logged in user
            responses:
                200:
                    description: Users details returned
/person:
    post:
        displayName: Add person
        description: |
            Add person
        body:
            schema:
                !include schema/request/person/post.json
    /list:
        get:
            displayName: List all people
            description: |
                List all people
            responses:
                200:
                    description: List of all people

    /{person_id}:
        get:
            displayName: Get person
            description: |
                Get a person
        put:
            displayName: person update
            description: |
                Update a person
            body:
                schema:
                    !include schema/request/person/put.json

        delete:
            displayName: person delete
            description: |
                Delete a person
