#%RAML 0.8
---
title: Test API
baseUri: http://api.foo.com/v2
version: v1
mediaType: application/json
protocols: [HTTPS, HTTP]

traits:
    - authenticated:
        usage: Apply to any method which requires a user to be authenticated via JWT
/body:
    /test1:
        get:
            displayName: test for this.body
            description: |
                Uses this.body to override the standard data structure
            responses:
                200:
                    description: statusCode, message not returned, only pure data
/user:
    /whoami:
        get:
            is: [authenticated]
            displayName: Who am I?
            description: |
                Get details on the logged in user
            responses:
                200:
                    description: Users details returned
/errors:
    /418:
        get:
            displayName: 418 error
            description: |
                throws a 418 error
            responses:
                500:
                    description: error test
    /500:
        get:
            displayName: 500 internal server error
            description: |
                throws a 500 error
            responses:
                500:
                    description: error test
/person:
    post:
        displayName: Add person
        description: |
            Add person
        body:
            schema:
                !include schema/request/person/post.json
    /list:
        get:
            displayName: List all people
            description: |
                List all people
            responses:
                200:
                    description: List of all people

    /{person_id}:
        get:
            displayName: Get person
            description: |
                Get a person
        put:
            displayName: person update
            description: |
                Update a person
            body:
                schema:
                    !include schema/request/person/put.json

        delete:
            displayName: person delete
            description: |
                Delete a person
